public inherited sharing class OnboardingEnqueueOnboardingTailRequest {
    @InvocableVariable(label='Contract Id')
    public String contractId;

    @InvocableVariable(label='Opportunity Id')
    public String opportunityId;

    @InvocableVariable(label='Vendor Program Id')
    public String vendorProgramId;

    @InvocableVariable(label='Account Id')
    public String accountId;

    @InvocableVariable(label='Correlation Key')
    public String correlationKey;
}